version: '3.4'

services:
  vita.api:
    image: microsoft/dotnet
    container_name: vitaapi
    build:
      context: .
      dockerfile: ./Vita.Api/Dockerfile
    depends_on: 
    - mssql

  mssql:
    image: microsoft/mssql-server-linux
    container_name: mssql
    volumes:
     - d:/sql

    ports: 
      - "1533:1433"
    environment:
      - "SA_PASSWORD=Vita123!@#"
      - "ACCEPT_EULA=Y"
      #- 'attach_dbs=[{"dbName":"customDB_test","dbFiles":["C:\\data\\customDB_test.mdf","C:\\data\\customDB_test.ldf"]}]'

volumes:
  mssqldata: 

networks:
  default:
    external:
      name: nat